stages:
  - verify

build:
  tags:
    - argus
    - docker-image
  stage: verify

  variables:
    CR_TOKEN: $CR_TOKEN
    CR_USER: $CR_USER
    TAG: $CI_COMMIT_TAG

  image:
    name: ghcr.io/epics-containers/ec-gitlab:0.1.0
    entrypoint: [""]

  script:
    - bash ./ci_verify.sh
